/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duanshopquanao;

import duanshopquanao.dao.QLKHDAO;
import duanshopquanao.model.QLKH;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY PC
 */
public class QuanLyKhachHang extends javax.swing.JFrame {

    List<QLKH> qlList = new ArrayList<>();
    int currentIndex = -1;

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyKhachHang() {
        initComponents();
        setLocationRelativeTo(null);
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnSearchTheoMA = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        btnBackLogin = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnTimTheoTen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quản Lý Khách Hàng");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã Khách Hàng:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên Khách Hang:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số điện thoại:");

        btnSearchTheoMA.setForeground(new java.awt.Color(102, 102, 255));
        btnSearchTheoMA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanshopquanao/icons8-search-in-browser-20.png"))); // NOI18N
        btnSearchTheoMA.setText("Tìm kiếm theo mã");
        btnSearchTheoMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTheoMAActionPerformed(evt);
            }
        });

        btnSave.setForeground(new java.awt.Color(102, 102, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanshopquanao/icons8-save-20.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setMaximumSize(new java.awt.Dimension(79, 27));
        btnSave.setMinimumSize(new java.awt.Dimension(79, 27));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setForeground(new java.awt.Color(102, 102, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanshopquanao/icons8-delete-20.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setForeground(new java.awt.Color(102, 102, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanshopquanao/icons8-update-20.png"))); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.setMaximumSize(new java.awt.Dimension(79, 27));
        btnUpdate.setMinimumSize(new java.awt.Dimension(79, 27));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblList.setBackground(java.awt.SystemColor.controlDkShadow);
        tblList.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblList.setForeground(new java.awt.Color(255, 255, 255));
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ tên ", "SDT", "Ngày mua hàng", "Mã hóa đơn"
            }
        ));
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        btnBackLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBackLogin.setForeground(new java.awt.Color(102, 153, 255));
        btnBackLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanshopquanao/icons8-back-20.png"))); // NOI18N
        btnBackLogin.setText("Về đăng nhập");
        btnBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLoginActionPerformed(evt);
            }
        });

        btnReset.setForeground(new java.awt.Color(102, 102, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanshopquanao/icons8-reset-20.png"))); // NOI18N
        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTimTheoTen.setForeground(new java.awt.Color(102, 102, 255));
        btnTimTheoTen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanshopquanao/icons8-search-in-browser-20.png"))); // NOI18N
        btnTimTheoTen.setText("Tìm kiếm theo tên");
        btnTimTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTheoTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchTheoMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimTheoTen)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(btnBackLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnBackLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSearchTheoMA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(62, 62, 62))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(49, 49, 49)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 870, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanshopquanao/shop1.1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        setSize(new java.awt.Dimension(1084, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        // TODO add your handling code here:
        selectThongTin();
    }//GEN-LAST:event_tblListMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        addKH();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateKH();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchTheoMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTheoMAActionPerformed
        // TODO add your handling code here:
        searchTheoMa();
    }//GEN-LAST:event_btnSearchTheoMAActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        deleteKH();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLoginActionPerformed
        // TODO add your handling code here:
        backToFormLogin();
    }//GEN-LAST:event_btnBackLoginActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTheoTenActionPerformed
        // TODO add your handling code here:
        searchNVtheoTen();
    }//GEN-LAST:event_btnTimTheoTenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackLogin;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchTheoMA;
    private javax.swing.JButton btnTimTheoTen;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
    public void backToFormLogin() {
        FromDangNhap lg = new FromDangNhap();
        lg.show();
    }

    public void loadDataToTable() {
        //Đọc tất cả dữ liệu trong table vào arraylist
        //Tạo title cho bảng
        qlList = QLKHDAO.getALL();
        String[] title = {"Mã khách hàng", "Tên khách hàng", "Số điện thoại"};
        DefaultTableModel model = new DefaultTableModel(title, 0);
        for (QLKH x : qlList) {
            model.addRow(new Object[]{x.getMaKH(), x.getTenKH(), x.getSoDT()});
        }
        tblList.setModel(model);
    }

//    public void inDataTable() {
//        qlList.add(new QLKH("KH01", "Trần Văn A", 0101001, "20/12/2012", "HD01"));
//        qlList.add(new QLKH("KH02", "Trần Văn b", 0101002, "20/12/2012", "HD02"));
//        qlList.add(new QLKH("KH03", "Trần Văn C", 0101002, "20/12/2012", "HD03"));
//
//    }
//    public void fillDataToTable() {
//        model = (DefaultTableModel) tblList.getModel();
//        model.setRowCount(0);
//        for (QLKH x : qlList) {
//            model.addRow(new Object[]{x.getMaKH(), x.getTenKH(), x.getSoDT(), x.getNgayMuaHang(), x.getMaHD()});
//        }
//    }
//
//    public void fillToControl(QLKH kh) {
//        txtMaKH.setText(kh.getMaKH());
//        txtTenKH.setText(kh.getTenKH());
//        txtSDT.setText(Integer.toString(kh.getSoDT()));
//        txtNgayMuaHang.setText(kh.getNgayMuaHang());
//    }
//
    public void selectThongTin() {
        currentIndex = tblList.getSelectedRow();
        txtMaKH.setText(tblList.getValueAt(currentIndex, 0).toString());
        txtTenKH.setText(tblList.getValueAt(currentIndex, 1).toString());
        txtSDT.setText(tblList.getValueAt(currentIndex, 2).toString());

    }
//
//    public QLKH readForm() {
//        return new QLKH(txtMaKH.getText(), txtTenKH.getText(), Integer.valueOf(txtSDT.getText()), txtNgayMuaHang.getText(), null);
//    }

    public boolean chkTrungMa(String s) {
        for (QLKH x : qlList) {
            if (x.getMaKH().equalsIgnoreCase(s)) {
                return true;
            }
            
        }
        return false;
    }

    public void reset() {
        txtMaKH.setText("");
        txtTenKH.setText("");
        txtSDT.setText("");

    }

    public boolean valiDateFormm() {
        if (txtMaKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mã khách hàng không được để trống", "Error", JOptionPane.ERROR_MESSAGE);
            txtMaKH.requestFocus();
            return false;
        }
        String pattennv = "^KH[0-9]{3}$";
        if (!(txtMaKH.getText()).matches(pattennv)) {
            JOptionPane.showMessageDialog(rootPane, "Mã khách hàng không hợp lệ", "Error", JOptionPane.ERROR_MESSAGE);
            txtMaKH.requestFocus();
            return false;
        }
        if (txtTenKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Tên khách hàng không được để trống", "Error", JOptionPane.ERROR_MESSAGE);
            txtTenKH.requestFocus();
            return false;
        }
        if (txtSDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại không được để trống", "Error", JOptionPane.ERROR_MESSAGE);
            txtSDT.requestFocus();
            return false;
        }      
        String patten = "^0[0-9]{9}$";
        if (!(txtSDT.getText().matches(patten))) {
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại không hợp lệ", "Error", JOptionPane.ERROR_MESSAGE);
            txtSDT.requestFocus();
            return false;
        }

        return true;
    }

    public void addKH() {
        if (valiDateFormm()) {
            if (chkTrungMa(txtMaKH.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Mã khách hàng đã tồn tại", "Error", JOptionPane.ERROR_MESSAGE);
                //Mã tồn tại
                return;
            }
            QLKH emp = new QLKH();
            emp.setMaKH(txtMaKH.getText());
            emp.setTenKH(txtTenKH.getText());
            emp.setSoDT(Integer.valueOf(txtSDT.getText()));
            int rs = QLKHDAO.insert(emp);
            if (rs > 0) {
                loadDataToTable();
                JOptionPane.showMessageDialog(rootPane, "Thêm khách hàng thành công");
                reset();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm khách hàng thất bại");

            }
        }
    }

    public void updateKH() {
        if (valiDateFormm()) {
            QLKH emp = new QLKH();
            emp.setMaKH(txtMaKH.getText());
            emp.setTenKH(txtTenKH.getText());
            emp.setSoDT(Integer.valueOf(txtSDT.getText()));
            int rs = QLKHDAO.update(emp);
            if (rs > 0) {
                loadDataToTable();
                JOptionPane.showMessageDialog(rootPane, "Cập nhật khách hàng thành công");
                reset();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật khách hàng thất bại");
            }
        }

    }

//    public void capnhat(QLKH newkh) {
//        
//            QLKH kh1 = findNv(newkh.getMaKH());
//            if (kh1 != null) {
//                kh1.setMaKH(newkh.getMaKH());
//                kh1.setTenKH(newkh.getTenKH());
//                kh1.setSoDT(newkh.getSoDT());
//                kh1.setNgayMuaHang(newkh.getNgayMuaHang());
//
//            
//        }
//    }
//
//    public QLKH findNv(String Ma) {
//        for (QLKH kh :  qlList) {
//            if (kh.getMaKH().equalsIgnoreCase(Ma)) {
//                return kh;
//            }
//        }
//        return null;
//    }
    public void searchTheoMa() {
        if (txtMaKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Cần nhập mã khách hàng để tìm", "Error", JOptionPane.ERROR_MESSAGE);
            txtMaKH.requestFocus();
            return;
        }

        try {
            Connection con = SQLConnect.connectionSQL();
            String sql = "select * from KHACHHANG where MAKH = ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txtMaKH.getText());
            ResultSet rs = st.executeQuery();
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(rootPane, "Thông tin khách hàng không tồn tại", "Error", JOptionPane.ERROR_MESSAGE);
                txtTenKH.setText("");
                txtSDT.setText("");
                return;
            }
            while (rs.next()) {
                if (txtMaKH.getText().equals(rs.getString(1))) {
                    txtTenKH.setText(rs.getString(2));
                    txtSDT.setText(rs.getString(3));
                    JOptionPane.showMessageDialog(rootPane, "Tìm thành công");
                }
            }

            con.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    public void searchNVtheoTen(){
        if(txtTenKH.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Cần nhập tên nhân viên để tìm","Error",JOptionPane.ERROR_MESSAGE);
            txtTenKH.requestFocus();
            return;
        }
        try {
            Connection con = SQLConnect.connectionSQL();
            String sql = "select * from KHACHHANG where HOTENKH like N'%" + txtTenKH.getText() + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(rootPane, "Thông tin nhân viên không tồn tại", "Error", JOptionPane.ERROR_MESSAGE);
                txtMaKH.setText("");
                txtTenKH.setText("");
                txtSDT.setText("");
                
                return;
            }
            while (rs.next()) {
                if (txtTenKH.getText().equalsIgnoreCase(rs.getString(2))) {
                    txtMaKH.setText(rs.getString(1));
                    txtSDT.setText(rs.getString(3));
                    JOptionPane.showMessageDialog(rootPane, "Tìm thành công");
                }

            }

            con.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    public void deleteKH() {
        if (txtMaKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mã khách hàng không được để trống, hãy nhập mã để xóa", "Error", JOptionPane.ERROR_MESSAGE);
            txtMaKH.requestFocus();
            return;
        }
        int luachon = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn xóa chứ?", "Delete", JOptionPane.YES_NO_OPTION);
        if (luachon == JOptionPane.YES_OPTION) {
            QLKH emp = new QLKH();
            emp.setMaKH(txtMaKH.getText());
            int rs = QLKHDAO.delete(emp);
            if (rs > 0) {
                loadDataToTable();
                JOptionPane.showMessageDialog(rootPane, "Xóa khách hàng thành công");
                reset();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Mã khách hàng không tồn tại", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            return;
        }
    }
}
