/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duanshopquanao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY PC
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    DefaultTableModel model;
    List<QLNV> nvList = new ArrayList<>();
    int currentIndex = -1;

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        setLocationRelativeTo(null);
        dataTotable();
        fillDataToTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtManhanvien = new javax.swing.JTextField();
        txtTenNhanVien = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        cboChucvu = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quản Lý Nhân Viên");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã nhân viên:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên  nhân viên:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Chức vụ:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lương:");

        Search.setForeground(new java.awt.Color(102, 102, 255));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        btnSave.setForeground(new java.awt.Color(102, 102, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setForeground(new java.awt.Color(102, 102, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setForeground(new java.awt.Color(102, 102, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblList.setBackground(java.awt.SystemColor.controlDkShadow);
        tblList.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblList.setForeground(new java.awt.Color(255, 255, 255));
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ tên ", "Chức vụ", "Lương"
            }
        ));
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        cboChucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vui lòng chọn", "Bán hàng", "Kế toán", "Quản lý" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtManhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 265, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtManhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(Search)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 870, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanshopquanao/shop4.1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        setSize(new java.awt.Dimension(1084, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        // TODO add your handling code here:
        selectNV();
    }//GEN-LAST:event_tblListMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        addNV();
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateNV();
        reset();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        searchNV();
    }//GEN-LAST:event_SearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        deleteNV();
        reset();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboChucvu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtManhanvien;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables

    public void dataTotable() {
        nvList.add(new QLNV("NV01", "Trần Quốc Thịnh", "Quản lý", 2000000.0));
        nvList.add(new QLNV("NV02", "Đỗ Tuấn Khải", "Bán hàng", 100000.0));
        nvList.add(new QLNV("NV03", "Huỳnh Phi Hùng", "Kế toán", 1200000.0));

    }

    public void fillDataToTable() {
        model = (DefaultTableModel) tblList.getModel();
        model.setRowCount(0);
        for (QLNV x : nvList) {
            model.addRow(new Object[]{x.getMaNV(), x.getTenNV(), x.getChucVu(), String.format("%,2f", x.getLuong())});
        }
    }

    public void selectNV() {
        currentIndex = tblList.getSelectedRow();
        fillDataControl(nvList.get(currentIndex));

    }

    public void fillDataControl(QLNV qlnv) {
        txtManhanvien.setText(qlnv.getMaNV());
        txtTenNhanVien.setText(qlnv.getTenNV());
        cboChucvu.setSelectedItem(qlnv.getChucVu());
        txtLuong.setText(Double.toString(qlnv.getLuong()));
    }

    public QLNV readForm() {
        return new QLNV(txtManhanvien.getText(), txtTenNhanVien.getText(), (String) cboChucvu.getSelectedItem(), Double.valueOf(txtLuong.getText()));
    }

    public boolean chkTrungMa(String s) {
        for (QLNV nv : nvList) {
            if (nv.getMaNV().equalsIgnoreCase(s)) {
                return true;
            }

        }
        return false;
    }

    public boolean validateForm() {
        if (txtManhanvien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Không được bỏ trống 'Mã'", "Error", JOptionPane.ERROR_MESSAGE);
            txtManhanvien.requestFocus();
            return false;
        }

        if (txtTenNhanVien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Không dược bỏ trống 'Tên'", "Error", JOptionPane.ERROR_MESSAGE);
            txtTenNhanVien.requestFocus();
            return false;
        }

        if (cboChucvu.getSelectedItem().equals("Vui lòng chọn")) {
            JOptionPane.showMessageDialog(rootPane, "Không được bỏ trống 'Chức vụ'", "Error", JOptionPane.ERROR_MESSAGE);
            cboChucvu.requestFocus();
            return false;
        }

        if (txtLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Không được bỏ trống 'Lương'", "Error", JOptionPane.ERROR_MESSAGE);
            txtLuong.requestFocus();
            return false;
        }

        try {
            Double.valueOf(txtLuong.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Lương phải là số", "Error", JOptionPane.ERROR_MESSAGE);
            txtLuong.requestFocus();
            return false;
        }

        if (Double.parseDouble(txtLuong.getText()) < 0) {
            JOptionPane.showMessageDialog(rootPane, "Lương không là số âm", "Error", JOptionPane.ERROR_MESSAGE);
            txtLuong.requestFocus();
            return false;
        }
        return true;
    }
    public void reset(){
        txtManhanvien.setText("");
        txtTenNhanVien.setText("");
        cboChucvu.setSelectedItem("vui lòng chọn");
        txtLuong.setText("");
    }

    public void addNV() {
        if (validateForm()) {
            if (chkTrungMa(txtManhanvien.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Mã nhân viên đã tổn tại", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            nvList.add(readForm());
            JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên thành công!");
            fillDataToTable();
        }
    }

    public void updateNV() {
            
            capnhat(readForm());
            fillDataToTable();
            JOptionPane.showMessageDialog(rootPane, "Cập nhật nhân viên thành công");
        
    }

    public void capnhat(QLNV newnv) {
        if (validateForm()) {
            QLNV nv1 = findNv(newnv.getMaNV());
            if (nv1 != null) {
                nv1.setMaNV(newnv.getMaNV());
                nv1.setTenNV(newnv.getTenNV());
                nv1.setChucVu(newnv.getChucVu());
                nv1.setLuong(newnv.getLuong());

            }
        }
    }

    public QLNV findNv(String Ma) {
        for (QLNV sp : nvList) {
            if (sp.getMaNV().equalsIgnoreCase(Ma)) {
                return sp;
            }
        }
        return null;
    }

    public void searchNV() {
        int i;
        String tim = JOptionPane.showInputDialog("Tìm nhân viên theo mã");
        if (tim.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Không đc bỏ trống ô tìm, mời bạn nhập lại");
            return;
        }
        for (i = 0; i < nvList.size(); i++) {
            QLNV qlnv = nvList.get(i);
            if (qlnv.getMaNV().equals(tim)) {
                JOptionPane.showMessageDialog(rootPane, "Tìm thành công nhân viên cần tìm");
                currentIndex = i;
                fillDataControl(qlnv);
                break;
            }
        }
        if (i == nvList.size()) {
            JOptionPane.showMessageDialog(rootPane, "Mã nhân viên không tồn tại");
        }
    }

    public void deleteNV() {
        if (txtManhanvien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mã nhân viên không được bỏ trống.Hãy nhập mã vào ô mã nhân viên để xóa", "Error", JOptionPane.ERROR_MESSAGE);
            txtManhanvien.requestFocus();
            return;
        }
        for (QLNV ql : nvList) {
            if (txtManhanvien.getText().equals(ql.getMaNV())) {
                int options = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn xóa chứ?", "Delete", JOptionPane.YES_NO_OPTION);
                if (options == JOptionPane.YES_OPTION) {
                    nvList.remove(ql);
                    fillDataToTable();
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                    return;
                } else {
                    return;
                }
            }
        }
    }
}
